### ISSUE TITLE
Error 500 with imports

### ISSUE THREAD

**Issue by thomasfischer089** [Michael-fore/Flask_IIS#1]
Your Hello World tutorial works like a charm.
But when I try do edit it with a few imports like pandas or plotly. I got an 500 error that ended unexpectedly.

Do you know a solutions. I think it has do something withe library import.

**Comment by Michael-fore** [comment]
Hi! 
Sorry for taking so long to get back

Make sure the environment you have running the process also has the imports.

You should be able to take the python path out of the iis config, run it in a terminal and import your libraries.

**Comment by Michael-fore** [comment]
Im going to close this since it has been so long
